######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 17 08:02:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloWorld2.cpp
