######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 17 07:58:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HelloWorld.cpp
