######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 17 08:16:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += AgeEntry.cpp
